version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000

  frontend:
    build:
      context: ./frontend/app
      args: {}
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:4000/api
    depends_on:
      - backend
