apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: Backend-DevOps-App
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Backend-DevOps-App
  template:
    metadata:
      labels:
        app: Backend-DevOps-App
    spec:
      containers:
        - name: Backend-Container
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
