apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: Frontend-DevOps-App
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Frontend-DevOps-App
  template:
    metadata:
      labels:
        app: Frontend-DevOps-App
    spec:
      containers:
        - name: frontend-container
          image: hasanabdirahman/devops-frontend:v1
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
