name: CI/CD DevOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push-images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-backend:${{ github.sha }} ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-backend:${{ github.sha }}

      - name: Build Frontend Image
        run: |
          docker build \
            --build-arg REACT_APP_API_URL=http://backend-service:4000/api \
            -t ${{ secrets.DOCKER_USERNAME }}/devops-frontend:${{ github.sha }} \
            ./frontend/app
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-frontend:${{ github.sha }}

  deploy-to-terraform:
    name: Deploy EKS with Terraform
    runs-on: ubuntu-latest
    needs: build-and-push-images

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Clean Terraform directory
        run: rm -rf Terraform/.terraform Terraform/.terraform.lock.hcl

      - name: Terraform Init
        run: |
          cd Terraform
          terraform init


      - name: Terraform Plan
        run: |
          cd Terraform
          terraform plan

      - name: Terraform Apply
        run: |
          cd Terraform
          terraform apply -auto-approve


  deploy-to-kubernetes:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: deploy-to-terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.0'

      - name: Get kubeconfig from AWS EKS
        run: |
          aws eks update-kubeconfig --name <YOUR_EKS_CLUSTER_NAME> --region us-east-1

      - name: Deploy Backend
        run: |
          kubectl apply -f K8/backend/deployment.yaml
          kubectl apply -f K8/backend/service.yaml

      - name: Deploy Frontend
        run: |
          kubectl apply -f K8/frontend/deployment.yaml
          kubectl apply -f K8/frontend/service.yaml
