name: CI/CD DevOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push-images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Login to Docker Hub using secrets
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build and push backend image
      - name: Build Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-backend:${{ github.sha }} ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-backend:${{ github.sha }}

      # 4️⃣ Build and push frontend image
      - name: Build Frontend Image
        run: |
          docker build \
            --build-arg REACT_APP_API_URL=http://backend-service:4000/api \
            -t ${{ secrets.DOCKER_USERNAME }}/devops-frontend:${{ github.sha }} \
            ./frontend/app
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-frontend:${{ github.sha }}

  deploy-to-kubernetes:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push-images

    steps:
      # 1️⃣ Checkout repository (needed for manifests)
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup kubectl
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.0'

      # 3️⃣ Configure kubeconfig from GitHub secret
      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

      # 4️⃣ Deploy backend
      - name: Deploy Backend
        run: |
          kubectl apply -f K8/backend/deployment.yaml
          kubectl apply -f K8/backend/service.yaml

      # 5️⃣ Deploy frontend
      - name: Deploy Frontend
        run: |
          kubectl apply -f K8/frontend/deployment.yaml
          kubectl apply -f K8/frontend/service.yaml
