name: CI/CD DevOps Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: dev-eks-cluster
  CLUSTER_VERSION: 1.28

jobs:
  deploy-to-terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: List files in Terraform folder
        run: ls -l Terraform/

      - name: Clean Terraform cache
        run: rm -rf Terraform/.terraform Terraform/.terraform.lock.hcl

      - name: Terraform Init
        working-directory: Terraform
        run: terraform init -upgrade

      - name: Terraform Plan
        working-directory: Terraform
        run: terraform plan \
          -var="aws_region=${{ env.AWS_REGION }}" \
          -var="cluster_name=${{ env.CLUSTER_NAME }}" \
          -var="cluster_version=${{ env.CLUSTER_VERSION }}"

      - name: Terraform Apply
        working-directory: Terraform
        run: terraform apply -auto-approve \
          -var="aws_region=${{ env.AWS_REGION }}" \
          -var="cluster_name=${{ env.CLUSTER_NAME }}" \
          -var="cluster_version=${{ env.CLUSTER_VERSION }}"
