name: CI/CD Devops Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push-images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Login to Docker Hub
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build backend image
      - name: Build Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-backend:${{ github.sha }} ../../backend
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-backend:${{ github.sha }}

      # 4️⃣ Build frontend image with backend URL
      - name: Build Frontend Image
        run: |
          docker build \
            --build-arg REACT_APP_API_URL=http://backend-service:4000/api \
            -t ${{ secrets.DOCKER_USERNAME }}/devops-frontend:${{ github.sha }} \
            ../../frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-frontend:${{ github.sha }}

  deploy-to-kubernetes:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push-images

    steps:
      # 1️⃣ Checkout repository (needed if manifests are in repo)
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup kubectl
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.0'

      # 3️⃣ Configure kubeconfig from GitHub secret
      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

      # 4️⃣ Deploy backend using YAML
      - name: Deploy Backend
        run: kubectl apply -f ../../K8/backend/backend-deployment.yaml

      # 5️⃣ Deploy frontend using YAML
      - name: Deploy Frontend
        run: kubectl apply -f ../../K8/frontend/frontend-deployment.yaml
